routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

/*Route::get('/', function () {
return view('welcome');
});*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

Auth::routes();

//Route::get('/home', 'HomeController@index');

Route::get('/', 'UserController@direcciona');

/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
 */

Route::group(['prefix' => 'api', 'namespace' => 'API'], function () {
	Route::group(['prefix' => 'v1'], function () {
		require config('infyom.laravel_generator.path.api_routes');
	});
});

Route::group(['middleware' => 'auth'], function () {

	Route::resource('hotels', 'HotelController');

	Route::resource('posts', 'PostController');

	Route::resource('habitaciones', 'HabitacionesController');

	Route::get('muestraHabitaciones/{idHotel}', 'HotelController@muestraHabitaciones');
//Route::get('muestraPisos/{idHotel}', 'PisosController@muestraPisos');
	Route::get('pisosHotel/{idHotel}', 'PisosController@pisosHotel')->name('pisosHotel');
	Route::get('piso/{idHotel}/{idPiso?}', 'PisosController@piso')->name('piso');
	Route::get('pisos/{idHotel}', 'PisosController@pisos')->name('pisos');
	Route::post('guarda_piso/{idPiso?}', 'PisosController@guarda_piso')->name('guarda_piso');
	Route::get('nuevaHabitacion/{idHotel}', 'HabitacionesController@nuevahabitacion');
	Route::get('ingresaPrecio/{idHabitacion}', 'PrecioshabitacionesController@ingresaPrecio');
	Route::get('asignahabitacion', 'ClientesController@asignahabitacion');
	Route::get('asignahabitacion2/{tipo}/{idCliente}/{num_reg?}', 'ClientesController@asignahabitacion2')->name('asignahabitacion2');
	/*Route::controller('datatables', 'PisosController', [
		        'anyData'  => 'datatables.data',
		        'muestraPisos' => 'datatables',
	*/

	Route::resource('clientes', 'ClientesController');

	Route::get('datatables/anyData', 'ClientesController@anyData')->name('datatables.data');
//    Route::get('datatables/getIndex', 'ClientesController@getIndex')->name('datatables');

	Route::resource('pisos', 'PisosController');

	Route::resource('precioshabitaciones', 'PrecioshabitacionesController');

	Route::resource('estudiantes', 'EstudiantesController');

//`Route::auth();

	Route::resource('cajas', 'CajaController');

	Route::resource('flujos', 'FlujoController');

	Route::get('caja/flujos/{idCaja}', 'CajaController@flujos')->name('flujos');

//Route::get('cajas2/{idHotel?}', 'CajaController@index')->name('cajas.index');

	Route::get('caja/ingreso/{idCaja}', 'CajaController@ingreso');
	Route::post('caja/guarda_ingreso', 'CajaController@guarda_ingreso');
	Route::post('retirarpagos', 'CajaController@retirarpagos')->name('retirarpagos');
	Route::post('retirarpagosdia', 'CajaController@retirarpagosdia')->name('retirarpagosdia');

	Route::get('caja/egreso/{idCaja}', 'CajaController@egreso');

	Route::get('soloingresos/{idCaja}', 'CajaController@soloingresos')->name('soloingresos');
	Route::get('soloingresosdia/{idCaja}', 'CajaController@soloingresosdia')->name('soloingresosdia');
	Route::get('ultimosretiros/{idCaja}', 'CajaController@ultimosretiros')->name('ultimosretiros');

	Route::post('caja/guarda_egreso', 'CajaController@guarda_egreso');
	Route::post('caja/eliminar_flujo/{idFlujo}', 'CajaController@eliminar_flujo');

	Route::get('caja/eliminaflujo/{idFlujo}', 'CajaController@eliminaflujo')->name('eliminaflujo');

	Route::get('detalleflujo/{idFlujo}', 'FlujoController@detalleflujo')->name('detalleflujo');

	Route::resource('registros', 'RegistroController');
	Route::get('registros', 'RegistroController@index')->name('registros');
	Route::get('registros/nuevo/{tipo}/{idCliGru}/{idHabitacion}/{idRegistro?}', 'RegistroController@nuevo')->name('nuevoregistro');
	Route::get('registros_calendario', 'RegistroController@calendario')->name('calendario');
	Route::post('registros/guarda_registro/{idRegistro?}', 'RegistroController@guarda_registro')->name('guarda_registro');
//Route::post('registros/nuevos/{idCliente}/{num_reg?}', 'RegistroController@nuevos')->name('nuevos');
	Route::post('registros/guarda_registros/{num_reg?}', 'RegistroController@guarda_registros')->name('guarda_registros');
	Route::get('registros_cliente/{idCliente}', 'RegistroController@registros_cliente')->name('registros_cliente');
	Route::post('registrar_pago', 'RegistroController@registrar_pago')->name('registrar_pago');

	Route::match(['get', 'post'], 'registros/nuevos/{idCliente}/{num_reg?}', 'RegistroController@nuevos')->name('nuevos');

	Route::get('get_num_reg', 'RegistroController@get_num_reg');

	Route::get('direcciona', 'UserController@direcciona')->name('direcciona');

	Route::get('usuarios/', 'UserController@index')->name('usuarios');
	Route::get('usuarios/usuario/{idUsuario?}', 'UserController@usuario')->name('usuario');
	Route::post('usuarios/guarda_usuario/{idUsuario?}', 'UserController@guarda_usuario')->name('guarda_usuario');
	Route::get('usuarios/eliminar/{idUsuario}', 'UserController@eliminar')->name('eliminar');

	Route::get('cambiarhotel/{idHotel}', 'UserController@cambiarhotel')->name('cambiarhotel');

	Route::get('vhabitaciones', 'HabitacionesController@vhabitaciones')->name('vhabitaciones');
	Route::get('informacion_habitacion/{idHabitacion}', 'HabitacionesController@informacion_habitacion')->name('informacion_habitacion');

	Route::resource('categorias', 'CategoriaController');

	Route::resource('facturas', 'FacturaController');
	Route::get('tutoriales', 'TutorialesController@index')->name('tutoriales');
	Route::get('tutoriales/operariotutoriales', 'TutorialesController@operariotutoriales')->name('opetutoriales');

	Route::get('facturar/{idFlujo}', 'FacturaController@facturar')->name('facturar');
	Route::post('generar_factura', 'FacturaController@generar_factura')->name('generar_factura');
	Route::get('factura/{idFactura}', 'FacturaController@factura')->name('factura');

//Route::get('reporte_pagos', 'ReporteController@reporte_pagos')->name('reporte_pagos');

	Route::match(['get', 'post'], 'reporte_pagos', 'ReporteController@reporte_pagos')->name('reporte_pagos');
	Route::match(['get', 'post'], 'repo_pago_regis', 'ReporteController@repo_pago_regis')->name('repo_pago_regis');
	Route::match(['get', 'post'], 'repo_pago_retirados', 'ReporteController@repo_pago_retirados')->name('repo_pago_retirados');

	Route::get('cliente/{idCliente?}', 'ClientesController@cliente')->name('cliente');
	Route::get('adjuntos/{idCliente}', 'ClientesController@adjuntos')->name('adjuntos');

	Route::post('guarda_cliente/{idCliente?}', 'ClientesController@guarda_cliente')->name('guarda_cliente');

	Route::post('guarda_s_adjunto/{idCliente}', 'ClientesController@guarda_s_adjunto')->name('guarda_s_adjunto');

	Route::get('elimina_adjunto/{idAdjunto}', 'ClientesController@elimina_adjunto')->name('elimina_adjunto');

	Route::get('quitarhuesped/{idHospedante}', 'RegistroController@quitarhuesped')->name('quitarhuesped');

	Route::get('msalidahuesped/{idHospedante}', 'RegistroController@msalidahuesped')->name('msalidahuesped');

	Route::get('grupos', 'GrupoController@index')->name('grupos');
	Route::get('registrosgrupos/{idGrupo}', 'GrupoController@registrosgrupos')->name('registrosgrupos');
	Route::get('grupo/{idGrupo?}', 'GrupoController@grupo')->name('grupo');
	Route::get('eliminargrupo/{idGrupo}', 'GrupoController@eliminargrupo')->name('eliminargrupo');
	Route::post('registrapagosg', 'GrupoController@registrapagosg')->name('registrapagosg');

	Route::get('informe_pago_grupo/{idGrupo}', 'GrupoController@informe_pago_grupo')->name('informe_pago_grupo');

	Route::get('marcasalida/{idRegistro}', 'GrupoController@marcasalida')->name('marcasalida');
	Route::get('cancelaregistro/{idRegistro}', 'GrupoController@cancelaregistro')->name('cancelaregistro');
	Route::get('generadeudasgrupos/{idGrupo}', 'GrupoController@generadeudasgrupos')->name('generadeudasgrupos');
	Route::get('generaadelantosgrupos/{idGrupo}', 'GrupoController@generaadelantosgrupos')->name('generaadelantosgrupos');

	Route::get('grupo/{idGrupo}', 'GrupoController@grupo')->name('grupo');
	Route::post('guarda_grupo/{idGrupo}', 'GrupoController@guarda_grupo')->name('guarda_grupo');
	Route::get('addpagoextra/{idRegistro}', 'GrupoController@addpagoextra')->name('addpagoextra');
	Route::post('guarda_pagoextra', 'GrupoController@guarda_pagoextra')->name('guarda_pagoextra');

	Route::match(['get', 'post'], 'pasajeros_reporte', 'ReporteController@pasajeros_reporte')->name('pasajeros_reporte');
	Route::match(['get', 'post'], 'reporte_registros', 'ReporteController@reporte_registros')->name('reporte_registros');

	Route::resource('actividads', 'ActividadController');
	Route::get('actividad/{idCliente}/{idActividad?}', 'ActividadController@actividad')->name('actividad');
	Route::post('guarda_actividad/{idActividad?}', 'ActividadController@guarda_actividad')->name('guarda_actividad');
	Route::get('grupos/eliminapago/{idPago}', 'GrupoController@eliminapago')->name('eliminapago');
	Route::post('grupos/eliminar_pago/{idPago}', 'GrupoController@eliminar_pago');
	Route::get('crono_genera_pagos', 'GrupoController@crono_genera_pagos');

	Route::post('opcioneshab', 'PisosController@opcioneshab')->name('opcioneshab');
	Route::post('guarda_precio_h', 'PisosController@guarda_precio_h')->name('guarda_precio_h');
	Route::post('elimina_precio_h', 'PisosController@elimina_precio_h')->name('elimina_precio_h');

	Route::get('imp_registro/{idRegistro}', 'RegistroController@imp_registro')->name('imp_registro');

app/Grupo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class Grupo extends Model
{
    //
    /*public function registros(){
        return $this->hasMany('\App\Models\Registro','grupo_id');
    }*/
    public function getDeudasAttribute()
    {

        $deuda = DB::table('pagos')
            ->leftJoin('registros', 'pagos.registro_id', '=', 'registros.id')
            ->select(DB::raw('SUM(pagos.monto_total) as monto_total'))
            ->where('registros.grupo_id', '=', $this->id)
            ->whereIn('pagos.estado',['Deuda','Deuda Extra'])
            ->groupBy('registros.grupo_id')
            ->first();
        if(isset($deuda)){
            return $deuda->monto_total;
        }else{
            return 0.00;
        }


    }
    public function responsable(){
        return $this->belongsTo('\App\Models\Clientes','responsable_id');
    }
}

app/Models/Habitaciones.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="Habitaciones",
 *      required={},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="hotel_id",
 *          description="hotel_id",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="piso",
 *          description="piso",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="nombre",
 *          description="nombre",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="estado",
 *          description="estado",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="observaciones",
 *          description="observaciones",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class Habitaciones extends Model
{
    use SoftDeletes;

    public $table = 'habitaciones';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'piso_id',
        'camas',
        'piso',
        'nombre',
        'estado',
        'observaciones',
        'categoria_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    /*
    protected $casts = [
        //'piso_id' => 'integer',
        'nombre' => 'string',
        'estado' => 'string',
        'observaciones' => 'string'
    ];
    */

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];


    public function rpiso(){
        //return $this->belongsTo('\App\Models\Pisos');
        return $this->belongsTo('\App\Models\Pisos', 'piso_id');
    }
    public function categoria(){
        //return $this->belongsTo('\App\Models\Pisos');
        return $this->belongsTo('\App\Models\Categoria', 'categoria_id');
    }

    /*public function registro(){
        return $this->belongsTo('\App\Models\Registro');
    }*/
    public function rprecios(){
        return $this->hasMany('\App\Models\Precioshabitaciones','habitacione_id');
    }

    /*public function registros(){
        return $this->hasMany('\App\Models\Registro','habitacione_id');
    }*/

    public function registrosactivos(){
        return $this->hasMany('\App\Models\Registro','habitacione_id')->whereIn('estado', ['Ocupando','Reservado']);

    }
    public function GetEstaocupadoAttribute(){
        $estadoo = $this->hasMany('\App\Models\Registro','habitacione_id')->where('estado', 'Ocupando')->first();
        if(isset($estadoo)){
            return true;
        }else{
            return false;
        }
    }
    public function GetEstareservadoAttribute(){
        $estadoo = $this->hasMany('\App\Models\Registro','habitacione_id')->where('estado', 'Reservado')->first();
        if(isset($estadoo)){
            return true;
        }else{
            return false;
        }
    }

}

resources/views/habitaciones/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <h1 class="pull-left">Nueva Habitacion</h1>
        </div>
    </div>

    @include('core-templates::common.errors')

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                {!! Form::open(['route' => 'habitaciones.store']) !!}
                <div class="box-body">
                    @include('habitaciones.fields')
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/habitaciones/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <h1 class="pull-left">Edit Habitaciones</h1>
        </div>
    </div>

    @include('core-templates::common.errors')

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                {!! Form::model($habitaciones, ['route' => ['habitaciones.update', $habitaciones->id], 'method' => 'patch']) !!}
                <div class="box-body">
                    @include('habitaciones.fields')
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/habitaciones/fields.blade.php
<!-- Hotel Id Field -->
<div class="form-group col-sm-6">
    {{--    {!! dd($pisosHotel) !!}--}}
    {!! Form::label('piso_id', 'Piso:') !!}
    {!! Form::select('piso_id', $pisosHotel,null, ['class' => 'form-control','placeholder' => 'Seleccione el piso','required']) !!}

</div>

<!-- Nombre Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nombre', 'Nombre:') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control', 'required']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('camas', 'Camas por habitacion:') !!}
    {!! Form::text('camas', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('categoria_id', 'Categoria:') !!}
    {!! Form::select('categoria_id', $categorias,null, ['class' => 'form-control','placeholder' => 'Seleccione la categoria','required']) !!}
</div>

<!-- Estado Field -->
<div class="form-group col-sm-6">
    {!! Form::label('estado', 'Estado:') !!}
    {!! Form::select('estado', ['Habilitado' => 'Habilitado','Deshabilitado' => 'Deshabilitado','Limpieza' => 'Limpieza'],null, ['class' => 'form-control','placeholder' => 'Seleccione el estado']) !!}
</div>

<!-- Observaciones Field -->
<div class="form-group col-sm-6">
    {!! Form::label('observaciones', 'Observaciones:') !!}
    {!! Form::text('observaciones', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('pisosHotel',[$idHotel]) !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/habitaciones/index.blade.php
@extends('layouts.app')

@section('content')

        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        @include('habitaciones.table')
        
@endsection

resources/views/habitaciones/informacion_habitacion.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">{!! $habitacion->nombre !!}</h4>
</div>

<div class="modal-body">
    <div class="form-group">
        <div class="row">
            <div class="col-md-12" style="font-size: 15px;">
                <table class="table table-bordered">
                    <tr>
                        <td><b>Habitacion:</b></td>
                        <td>{!! $habitacion->nombre !!}</td>
                        <td><b>Piso:</b></td>
                        <td>{!! $habitacion->rpiso->nombre !!}</td>

                    </tr>
                    <tr>
                        <td><b>Categoria:</b></td>
                        <td>
                            @if(isset($habitacion->categoria->nombre))
                                {!! $habitacion->categoria->nombre !!}
                            @endif
                        </td>
                        <td><b></b></td>
                        <td></td>
                    </tr>
                </table>

                <table class="table table-bordered">

                    @foreach($habitacion->registrosactivos as $registro)
                        <?php
                        $color_reg = 'info';
                        $fechass = "";
                        if ($registro->estado == 'Ocupando') {
                            $color_reg = 'danger';
                            $fechass = $registro->fecha_ingreso;
                        } elseif ($registro->estado == 'Reservado') {
                            $color_reg = 'warning';
                            $fechass = $registro->fech_ini_reserva2 . ' - ' . $registro->fech_fin_reserva2;
                        }
                        ?>
                        <tr class="btn-{!! $color_reg !!}" style="cursor: pointer;" onclick="window.location.href = '{!! route('registrosgrupos',[$registro->grupo_id]) !!}';">
                            <td>{!! $registro->estado !!}</td>
                            <td>{!! $registro->grupo->nombre !!}</td>
                            <td>
                                {!! $fechass !!}
                            </td>
                            <td><b>{!! $registro->grupo->deudas !!} </b>Bs</td>
                        </tr>
                    @endforeach
                </table>

            </div>
            


           <!--  if($habitacion->id != $registro->habitacione_id    )
            

             if ($habitacion->estado == 'Habilitado' || $habitacion->estado == 'Limpieza' || $habitacion->estado == 'Deshabilitado' )  

 -->
            {!! Form::model($habitacion, ['route' => ['guarda_habitacion_es', $habitacion->id], 'method' => 'post','id' => 'idformhab']) !!}
            <div class="form-group col-sm-12">
                {!! Form::label('estado', 'Estado:') !!}
                {!! Form::select('estado', ['Habilitado' => 'Habilitado','Deshabilitado' => 'Deshabilitado','Limpieza' => 'Limpieza'],null, ['class' => 'form-control','id' => 'idselestado']) !!}
            </div>

           
            



            <!-- if( $registro->estado != 'Ocupando')
            if( $registro->estado != 'Reservado')

            
           
            endif 



            endif -->
           

            
            {!! Form::close() !!}
        </div>
    </div>
</div>
{!! Form::open(['route' => ['habitaciones.destroy', $habitacion->id], 'method' => 'delete']) !!}
<div class="modal-footer">
    <?php
    $role = Auth::user()->rol;
    ?>
    @if($role != 'Operario')
        <a href="{!! route('habitaciones.edit', [$habitacion->id]) !!}" class='btn btn-outline pull-left'>Editar</a>
        <a href="{!! url('ingresaPrecio', [$habitacion->id]) !!}" class='btn btn-outline pull-left'>Precios</a>
        @if (isset($habitacion->registro_id))
            <a href="javascript:"
               onclick="cargarmodal('{!! route('nuevoregistro',[$habitacion->registro->cliente_id,$habitacion->id,$habitacion->registro_id]) !!}','warning')"
               class='btn btn-outline pull-left' title="Registro">Registro</a>
        @endif

        {!! Form::button('Eliminar', ['type' => 'submit', 'class' => 'btn btn-outline pull-left', 'onclick' => "return confirm('Esta seguro de eliminar?')"]) !!}
    @endif
    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Cerrar</button>
</div>
{!! Form::close() !!}


<script>
    $('#idselestado').on('change',function(){
        $('#idformhab').submit();
    });
</script>

resources/views/habitaciones/show.blade.php
@extends('layouts.app')

@section('content')
    @include('habitaciones.show_fields')

    <div class="form-group">
           <a href="{!! route('habitaciones.index') !!}" class="btn btn-default">Back</a>
    </div>
@endsection

resources/views/habitaciones/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $habitaciones->id !!}</p>
</div>

<!-- Hotel Id Field -->
<div class="form-group">
    {!! Form::label('hotel_id', 'Hotel Id:') !!}
    <p>{!! $habitaciones->hotel_id !!}</p>
</div>

<!-- Piso Field -->
<div class="form-group">
    {!! Form::label('piso', 'Piso:') !!}
    <p>{!! $habitaciones->piso !!}</p>
</div>

<!-- Nombre Field -->
<div class="form-group">
    {!! Form::label('nombre', 'Nombre:') !!}
    <p>{!! $habitaciones->nombre !!}</p>
</div>

<!-- Estado Field -->
<div class="form-group">
    {!! Form::label('estado', 'Estado:') !!}
    <p>{!! $habitaciones->estado !!}</p>
</div>

<!-- Observaciones Field -->
<div class="form-group">
    {!! Form::label('observaciones', 'Observaciones:') !!}
    <p>{!! $habitaciones->observaciones !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $habitaciones->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $habitaciones->updated_at !!}</p>
</div>

resources/views/habitaciones/table.blade.php
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Listado de habitaciones</h3>
                <div class="box-tools pull-right no-imprimir">
                    <button class="btn btn-box-tool btn-success" title="Editar" onclick="window.location.href = '{!! route('habitaciones.create') !!}';" style="color: #ffffff;"><i class="fa fa-plus"></i> <b>Nueva habitacion</b></button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-responsive table-bordered" id="tabla">
                    <thead>
                    <th>Piso</th>
                    <th>Nombre</th>
                    <th>Cliente</th>
                    <th>Fechas</th>
                    <th>Observaciones</th>
                    <th>Action</th>
                    </thead>
                    <tbody>
                    @foreach($habitaciones as $habitaciones)
                        <tr>
                            <td>{!! $habitaciones->piso_id !!}</td>
                            <td>{!! $habitaciones->nombre !!}</td>
                            <td>{{ isset($habitaciones->registro->cliente->nombre) ? $habitaciones->registro->cliente->nombre : '' }}</td>
                            <td>{{ isset($habitaciones->registro) ? $habitaciones->registro->fecha_ingreso.' - '.$habitaciones->registro->fecha_salida  : '' }}</td>
                            <td>{{ isset($habitaciones->registro) ? $habitaciones->registro->observacion : '' }}</td>
                            <td>
                                {!! Form::open(['route' => ['habitaciones.destroy', $habitaciones->id], 'method' => 'delete']) !!}
                                <div class='btn-group'>
                                    <a href="{!! route('habitaciones.show', [$habitaciones->id]) !!}"
                                       class='btn btn-default btn-xs'><i
                                                class="glyphicon glyphicon-eye-open"></i></a>
                                    <a href="{!! route('habitaciones.edit', [$habitaciones->id]) !!}"
                                       class='btn btn-default btn-xs'><i
                                                class="glyphicon glyphicon-edit"></i></a>
                                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                                </div>
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


@push('scriptsextras')
@include('layouts.partials.jsdatatable')
@endpush