routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

/*Route::get('/', function () {
return view('welcome');
});*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

Auth::routes();

//Route::get('/home', 'HomeController@index');

Route::get('/', 'UserController@direcciona');

/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
 */

Route::group(['prefix' => 'api', 'namespace' => 'API'], function () {
	Route::group(['prefix' => 'v1'], function () {
		require config('infyom.laravel_generator.path.api_routes');
	});
});

Route::group(['middleware' => 'auth'], function () {

	Route::resource('hotels', 'HotelController');

	Route::resource('posts', 'PostController');

	Route::resource('habitaciones', 'HabitacionesController');

	Route::get('muestraHabitaciones/{idHotel}', 'HotelController@muestraHabitaciones');
//Route::get('muestraPisos/{idHotel}', 'PisosController@muestraPisos');
	Route::get('pisosHotel/{idHotel}', 'PisosController@pisosHotel')->name('pisosHotel');
	Route::get('piso/{idHotel}/{idPiso?}', 'PisosController@piso')->name('piso');
	Route::get('pisos/{idHotel}', 'PisosController@pisos')->name('pisos');
	Route::post('guarda_piso/{idPiso?}', 'PisosController@guarda_piso')->name('guarda_piso');
	Route::get('nuevaHabitacion/{idHotel}', 'HabitacionesController@nuevahabitacion');
	Route::get('ingresaPrecio/{idHabitacion}', 'PrecioshabitacionesController@ingresaPrecio');
	Route::get('asignahabitacion', 'ClientesController@asignahabitacion');
	Route::get('asignahabitacion2/{tipo}/{idCliente}/{num_reg?}', 'ClientesController@asignahabitacion2')->name('asignahabitacion2');
	/*Route::controller('datatables', 'PisosController', [
		        'anyData'  => 'datatables.data',
		        'muestraPisos' => 'datatables',
	*/

	Route::resource('clientes', 'ClientesController');

	Route::get('datatables/anyData', 'ClientesController@anyData')->name('datatables.data');
//    Route::get('datatables/getIndex', 'ClientesController@getIndex')->name('datatables');

	Route::resource('pisos', 'PisosController');

	Route::resource('precioshabitaciones', 'PrecioshabitacionesController');

	Route::resource('estudiantes', 'EstudiantesController');

//`Route::auth();

	Route::resource('cajas', 'CajaController');

	Route::resource('flujos', 'FlujoController');

	Route::get('caja/flujos/{idCaja}', 'CajaController@flujos')->name('flujos');

//Route::get('cajas2/{idHotel?}', 'CajaController@index')->name('cajas.index');

	Route::get('caja/ingreso/{idCaja}', 'CajaController@ingreso');
	Route::post('caja/guarda_ingreso', 'CajaController@guarda_ingreso');
	Route::post('retirarpagos', 'CajaController@retirarpagos')->name('retirarpagos');
	Route::post('retirarpagosdia', 'CajaController@retirarpagosdia')->name('retirarpagosdia');

	Route::get('caja/egreso/{idCaja}', 'CajaController@egreso');

	Route::get('soloingresos/{idCaja}', 'CajaController@soloingresos')->name('soloingresos');
	Route::get('soloingresosdia/{idCaja}', 'CajaController@soloingresosdia')->name('soloingresosdia');
	Route::get('ultimosretiros/{idCaja}', 'CajaController@ultimosretiros')->name('ultimosretiros');

	Route::post('caja/guarda_egreso', 'CajaController@guarda_egreso');
	Route::post('caja/eliminar_flujo/{idFlujo}', 'CajaController@eliminar_flujo');

	Route::get('caja/eliminaflujo/{idFlujo}', 'CajaController@eliminaflujo')->name('eliminaflujo');

	Route::get('detalleflujo/{idFlujo}', 'FlujoController@detalleflujo')->name('detalleflujo');

	Route::resource('registros', 'RegistroController');
	Route::get('registros', 'RegistroController@index')->name('registros');
	Route::get('registros/nuevo/{tipo}/{idCliGru}/{idHabitacion}/{idRegistro?}', 'RegistroController@nuevo')->name('nuevoregistro');
	Route::get('registros_calendario', 'RegistroController@calendario')->name('calendario');
	Route::post('registros/guarda_registro/{idRegistro?}', 'RegistroController@guarda_registro')->name('guarda_registro');
//Route::post('registros/nuevos/{idCliente}/{num_reg?}', 'RegistroController@nuevos')->name('nuevos');
	Route::post('registros/guarda_registros/{num_reg?}', 'RegistroController@guarda_registros')->name('guarda_registros');
	Route::get('registros_cliente/{idCliente}', 'RegistroController@registros_cliente')->name('registros_cliente');
	Route::post('registrar_pago', 'RegistroController@registrar_pago')->name('registrar_pago');

	Route::match(['get', 'post'], 'registros/nuevos/{idCliente}/{num_reg?}', 'RegistroController@nuevos')->name('nuevos');

	Route::get('get_num_reg', 'RegistroController@get_num_reg');

	Route::get('direcciona', 'UserController@direcciona')->name('direcciona');

	Route::get('usuarios/', 'UserController@index')->name('usuarios');
	Route::get('usuarios/usuario/{idUsuario?}', 'UserController@usuario')->name('usuario');
	Route::post('usuarios/guarda_usuario/{idUsuario?}', 'UserController@guarda_usuario')->name('guarda_usuario');
	Route::get('usuarios/eliminar/{idUsuario}', 'UserController@eliminar')->name('eliminar');

	Route::get('cambiarhotel/{idHotel}', 'UserController@cambiarhotel')->name('cambiarhotel');

	Route::get('vhabitaciones', 'HabitacionesController@vhabitaciones')->name('vhabitaciones');
	Route::get('informacion_habitacion/{idHabitacion}', 'HabitacionesController@informacion_habitacion')->name('informacion_habitacion');

	Route::resource('categorias', 'CategoriaController');

	Route::resource('facturas', 'FacturaController');
	Route::get('tutoriales', 'TutorialesController@index')->name('tutoriales');
	Route::get('tutoriales/operariotutoriales', 'TutorialesController@operariotutoriales')->name('opetutoriales');

	Route::get('facturar/{idFlujo}', 'FacturaController@facturar')->name('facturar');
	Route::post('generar_factura', 'FacturaController@generar_factura')->name('generar_factura');
	Route::get('factura/{idFactura}', 'FacturaController@factura')->name('factura');

//Route::get('reporte_pagos', 'ReporteController@reporte_pagos')->name('reporte_pagos');

	Route::match(['get', 'post'], 'reporte_pagos', 'ReporteController@reporte_pagos')->name('reporte_pagos');
	Route::match(['get', 'post'], 'repo_pago_regis', 'ReporteController@repo_pago_regis')->name('repo_pago_regis');
	Route::match(['get', 'post'], 'repo_pago_retirados', 'ReporteController@repo_pago_retirados')->name('repo_pago_retirados');

	Route::get('cliente/{idCliente?}', 'ClientesController@cliente')->name('cliente');
	Route::get('adjuntos/{idCliente}', 'ClientesController@adjuntos')->name('adjuntos');

	Route::post('guarda_cliente/{idCliente?}', 'ClientesController@guarda_cliente')->name('guarda_cliente');

	Route::post('guarda_s_adjunto/{idCliente}', 'ClientesController@guarda_s_adjunto')->name('guarda_s_adjunto');

	Route::get('elimina_adjunto/{idAdjunto}', 'ClientesController@elimina_adjunto')->name('elimina_adjunto');

	Route::get('quitarhuesped/{idHospedante}', 'RegistroController@quitarhuesped')->name('quitarhuesped');

	Route::get('msalidahuesped/{idHospedante}', 'RegistroController@msalidahuesped')->name('msalidahuesped');

	Route::get('grupos', 'GrupoController@index')->name('grupos');
	Route::get('registrosgrupos/{idGrupo}', 'GrupoController@registrosgrupos')->name('registrosgrupos');
	Route::get('grupo/{idGrupo?}', 'GrupoController@grupo')->name('grupo');
	Route::get('eliminargrupo/{idGrupo}', 'GrupoController@eliminargrupo')->name('eliminargrupo');
	Route::post('registrapagosg', 'GrupoController@registrapagosg')->name('registrapagosg');

	Route::get('informe_pago_grupo/{idGrupo}', 'GrupoController@informe_pago_grupo')->name('informe_pago_grupo');

	Route::get('marcasalida/{idRegistro}', 'GrupoController@marcasalida')->name('marcasalida');
	Route::get('cancelaregistro/{idRegistro}', 'GrupoController@cancelaregistro')->name('cancelaregistro');
	Route::get('generadeudasgrupos/{idGrupo}', 'GrupoController@generadeudasgrupos')->name('generadeudasgrupos');
	Route::get('generaadelantosgrupos/{idGrupo}', 'GrupoController@generaadelantosgrupos')->name('generaadelantosgrupos');

	Route::get('grupo/{idGrupo}', 'GrupoController@grupo')->name('grupo');
	Route::post('guarda_grupo/{idGrupo}', 'GrupoController@guarda_grupo')->name('guarda_grupo');
	Route::get('addpagoextra/{idRegistro}', 'GrupoController@addpagoextra')->name('addpagoextra');
	Route::post('guarda_pagoextra', 'GrupoController@guarda_pagoextra')->name('guarda_pagoextra');

	Route::match(['get', 'post'], 'pasajeros_reporte', 'ReporteController@pasajeros_reporte')->name('pasajeros_reporte');
	Route::match(['get', 'post'], 'reporte_registros', 'ReporteController@reporte_registros')->name('reporte_registros');

	Route::resource('actividads', 'ActividadController');
	Route::get('actividad/{idCliente}/{idActividad?}', 'ActividadController@actividad')->name('actividad');
	Route::post('guarda_actividad/{idActividad?}', 'ActividadController@guarda_actividad')->name('guarda_actividad');
	Route::get('grupos/eliminapago/{idPago}', 'GrupoController@eliminapago')->name('eliminapago');
	Route::post('grupos/eliminar_pago/{idPago}', 'GrupoController@eliminar_pago');
	Route::get('crono_genera_pagos', 'GrupoController@crono_genera_pagos');

	Route::post('opcioneshab', 'PisosController@opcioneshab')->name('opcioneshab');
	Route::post('guarda_precio_h', 'PisosController@guarda_precio_h')->name('guarda_precio_h');
	Route::post('elimina_precio_h', 'PisosController@elimina_precio_h')->name('elimina_precio_h');

	Route::get('imp_registro/{idRegistro}', 'RegistroController@imp_registro')->name('imp_registro');

app/Models/Clientes.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * @SWG\Definition(
 *      definition="Clientes",
 *      required={nombre},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="nombre",
 *          description="nombre",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="nacionalidad",
 *          description="nacionalidad",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="edad",
 *          description="edad",
 *          type="string",
 *          format="date"
 *      ),
 *      @SWG\Property(
 *          property="procedencia",
 *          description="procedencia",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="profesion",
 *          description="profesion",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="pasaporte",
 *          description="pasaporte",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="ci",
 *          description="ci",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="celular",
 *          description="celular",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="referencia",
 *          description="referencia",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="estado",
 *          description="estado",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="direccion",
 *          description="direccion",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="observaciones",
 *          description="observaciones",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class Clientes extends Model
{
    use SoftDeletes;

    public $table = 'clientes';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'nombre',
        'nacionalidad',
        'edad',
        'procedencia',
        'profesion',
        'pasaporte',
        'ci',
        'celular',
        'referencia',
        'estado',
        'direccion',
        'observaciones',
        'deleted_at',
        'ruser_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nombre' => 'string',
        'nacionalidad' => 'string',
        'edad' => 'date',
        'procedencia' => 'string',
        'profesion' => 'string',
        'pasaporte' => 'string',
        'ci' => 'string',
        'celular' => 'string',
        'referencia' => 'string',
        'estado' => 'string',
        'direccion' => 'string',
        'observaciones' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nombre' => 'required'
    ];



    public function getEdad2Attribute()
    {
        $value = $this->edad;
        if (!empty($value) && "0000-00-00 00:00:00" != $value) {
            //$fecha = Carbon::parse($value);
            //return $fecha->format('y-m-d');
            $fecha = Carbon::parse($value);
            return $fecha->diff(Carbon::now())->format('%y');
        } else {
            return null;
        }
    }

    public function getIdentidadAttribute()
    {
        if(!empty($this->ci)){
            return $this->ci;
        }elseif (!empty($this->pasaporte)){
            return $this->pasaporte;
        }else{
            return null;
        }
    }

    public function actividades(){
        return $this->hasMany('\App\Models\Actividad','cliente_id')->orderBy('id','desc');
    }

    public function getEdad3Attribute()
    {
        $value = $this->edad;
        if (!empty($value) && "0000-00-00 00:00:00" != $value) {
            $fecha = Carbon::parse($value);
            return $fecha->format('Y-m-d');
        } else {
            return null;
        }
    }

    public function adjuntos(){
        return $this->hasMany('\App\Adjunto','cliente_id');
    }

    public function GetTieneadjuntosAttribute(){
        $estadoo = $this->hasMany('\App\Adjunto','cliente_id')->first();
        if(isset($estadoo)){
            return true;
        }else{
            return false;
        }
    }

    public function getEntregas($idHotel,$fecha = null){
        $rrr =  $this->hasMany('\App\Entrega','cliente_id')->where('deleted_at',null)->where('hotel_id',$idHotel)->where(DB::raw('DATE(created_at)'), '=', $fecha)->get();
        return $rrr;
    }
    public function entregas(){
        return $this->hasMany('\App\Entrega','cliente_id');
    }

}

resources/views/clientes/adjuntos.blade.php
<?php
function escoge($adjun)
{
    $array_f = explode('.', $adjun);
    $extension = end($array_f);
    $extension = strtoupper($extension);
    if((in_array($extension, array('JPEG','JPG','PNG')))){
        return $adjun;
    }elseif ($extension == 'PDF'){
        return "../img/logopdf.png";
    }else{
        return "../img/logofile.png";
    }
}
?>
{!! Form::model($cliente, ['route' => ['guarda_s_adjunto',$cliente->id], 'method' => 'post', 'files'=>true,'enctype' => 'multipart/form-data','id' => 'form-cliente']) !!}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">X</span>
    </button>
    <h4 class="modal-title">Archivos adjuntos del cliente</h4>
</div>
<div class="modal-body">
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered">
                    <tr>
                        <td><b>CLIENTE:</b></td>
                        <td>{!! $cliente->nombre !!}</td>
                    </tr>
                    <tr>
                        <td><b>CI/PASAPORTE:</b></td>
                        <td>
                            @if(!empty($cliente->ci))
                                {!! $cliente->ci !!}
                            @elseif(!empty($cliente->pasaporte))
                                {!! $cliente->pasaporte !!}
                            @endif
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="form-group" >
        <div class="row">
            <div class="col-md-8">
                <div class="row" id="adjunto-1">
                    <div class="col-md-4 text-right">
                        <b>ARCHIVO ADJUNTO 1</b>
                    </div>
                    <div class="col-md-8">
                        {!! Form::file('archivos[1][datos]') !!}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <button type="button" class="btn btn-success btn-sm" onclick="adicionar_a();"><i class="fa fa-plus"></i>
                    Adicionar
                </button>
                <button type="button" class="btn btn-danger btn-sm" onclick="quitar_a();"><i class="fa fa-minus"></i>
                    Quitar
                </button>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                @if(!empty($cliente->adjuntos->all()))
                    <table class="table table-bordered">
                        @foreach($cliente->adjuntos as $adjunto)
                            @if(empty($adjunto->deleted_at))
                            <tr>
                                <td align="center" style="padding: 0px;">
                                    <?php $nombre_ar = escoge($adjunto->nombre);?>
                                            <img class="img-responsive pad" style="max-height: 80px;" src="{!! url('adjuntos/'.$nombre_ar) !!}" alt="Product Image">


                                </td>
                                <td style="vertical-align: middle;">{!! $adjunto->nombre_original !!}</td>

                                <td style="vertical-align: middle;">

                                    <a href="{!! url('adjuntos/'.$adjunto->nombre) !!}" target="_blank"
                                       class="btn btn-success btn-sm" title="VER ARCHIVO"><i
                                                class="fa fa-eye"></i></a>
                                    <a href="javascript:"
                                       onclick="if(confirm('Esta seguro de eliminar el archivo adjunto??')){eliminar_adj({!! $adjunto->id !!});}"
                                       class="btn btn-danger btn-sm" title="Eliminar adjunto"><i
                                                class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                            @endif
                        @endforeach
                    </table>
                @else
                    <h4>NO TIENE ARCHIVOS ADJUNTOS!!!</h4>
                @endif
            </div>
        </div>
    </div>
</div>
{!! Form::hidden('ruser_id',Auth::user()->id) !!}
<div class="modal-footer">
    {!! Form::submit('Guardar', ['class' => 'btn btn-outline pull-left']) !!}
    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Cerrar</button>
</div>
{!! Form::close() !!}

<script>
    var n_adj = 1;
    function adicionar_a() {
        n_adj++;
        var cont_adj = $('#adjunto-1').html();
        $('#adjunto-' + (n_adj - 1)).after('<div class="row" id="adjunto-' + n_adj + '">' + cont_adj + '</div>');
        $('#adjunto-' + n_adj + ' div.text-right b').html('ARCHIVO ADJUNTO ' + n_adj);
        $('#adjunto-' + n_adj + ' input').attr('name', 'archivos[' + n_adj + '][datos]');
    }
    function quitar_a() {
        if (n_adj != 1) {
            $('#adjunto-' + n_adj).remove();
            n_adj--;
        }
    }
    $("#form-cliente").submit(function (e) {
        var postData = new FormData($(this)[0]);
        //console.log($(this));


        //var postData = $(this).serializeArray();
        //console.log(postData);
        //console.log(postData2);
        //e.preventDefault();

        var formURL = $(this).attr("action");
        $.ajax(
                {
                    url: formURL,
                    type: "POST",
                    data: postData,
                    async: false,
                    processData: false,
                    cache: false,
                    contentType: false,

                    beforeSend: function (XMLHttpRequest) {
                        //alert("antes de enviar");
                        $('#divmodal').hide();
                        jQuery("#spin-cargando-mod").show(200);
                    },
                    complete: function (XMLHttpRequest, textStatus) {
                        //alert('despues de enviar');
                    },
                    success: function (data, textStatus, jqXHR) {
                        //console.log(data);
                        setTimeout(function () {
                            jQuery("#spin-cargando-mod").hide();
                            $('#divmodal').show();
                            if (data['m_error'] == '') {
                                $('#mimodal').attr('class', 'modal modal-success');
                                $('#divmodal h4.modal-title').html(data['m_bueno']);
                                $('#divmodal div.modal-body').hide();
                                $('#divmodal div.modal-footer').hide();
                                setTimeout(function () {
                                    cargarmodal('{!! route('adjuntos',[$cliente->id]) !!}', 'info', 'lg');
                                    $('#mimodal').attr('class', 'modal modal-info');
                                    $('#divmodal div.modal-body').show();
                                    $('#divmodal div.modal-footer').show();
                                }, 1900);
                            } else {
                                $('#mimodal').attr('class', 'modal modal-danger');
                                $('#divmodal h4.modal-title').html(data['m_error']);
                                $('#divmodal div.modal-body').hide();
                                $('#divmodal div.modal-footer').hide();
                                setTimeout(function () {
                                    //$('#divmodal h4.modal-title').html('Formulario de Cliente');
                                    $('#divmodal div.modal-body').show();
                                    $('#divmodal div.modal-footer').show();
                                    //$('#mimodal').modal('hide');
                                    //recargatabla();
                                }, 1900);
                            }


                        }, 1000);

                        //data: return data from server
                        //$("#parte").html(data);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        //if fails
                        alert("error");
                    }
                });
        e.preventDefault(); //STOP default action
        //e.unbind(); //unbind. to stop multiple form submit.
    });
    @if(isset($cliente->id))
    function eliminar_adj(idAdjunto) {
        $.ajax(
                {
                    url: '{!! url('elimina_adjunto') !!}/' + idAdjunto,
                    type: "GET",
                    beforeSend: function (XMLHttpRequest) {
                        //alert("antes de enviar");
                        $('#divmodal').hide();
                        jQuery("#spin-cargando-mod").show(200);
                    },
                    complete: function (XMLHttpRequest, textStatus) {
                        //alert('despues de enviar');
                    },
                    success: function (data, textStatus, jqXHR) {
                        //console.log(data);
                        setTimeout(function () {
                            jQuery("#spin-cargando-mod").hide();
                            $('#divmodal').show();
                            if (data['m_error'] == '') {
                                $('#mimodal').attr('class', 'modal modal-success');
                                $('#divmodal h4.modal-title').html(data['m_bueno']);
                                $('#divmodal div.modal-body').hide();
                                $('#divmodal div.modal-footer').hide();
                                setTimeout(function () {
                                    cargarmodal('{!! route('adjuntos',[$cliente->id]) !!}', 'info', 'lg');
                                    $('#mimodal').attr('class', 'modal modal-info');
                                    $('#divmodal div.modal-body').show();
                                    $('#divmodal div.modal-footer').show();
                                }, 1900);
                            } else {
                                $('#mimodal').attr('class', 'modal modal-danger');
                                $('#divmodal h4.modal-title').html(data['m_error']);
                                $('#divmodal div.modal-body').hide();
                                $('#divmodal div.modal-footer').hide();
                                setTimeout(function () {
                                    //$('#divmodal h4.modal-title').html('Formulario de Cliente');
                                    $('#divmodal div.modal-body').show();
                                    $('#divmodal div.modal-footer').show();
                                    //$('#mimodal').modal('hide');
                                    //recargatabla();
                                }, 1900);
                            }


                        }, 1000);

                        //data: return data from server
                        //$("#parte").html(data);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        //if fails
                        alert("error");
                    }
                });
    }
    @endif
</script>

resources/views/clientes/fields.blade.php
<!-- Nombre Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nombre', 'Nombre:') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
</div>

<!-- Nacionalidad Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nacionalidad', 'Nacionalidad:') !!}
    {!! Form::text('nacionalidad', null, ['class' => 'form-control']) !!}
</div>

<!-- Edad Field -->
<div class="form-group col-sm-6">
    {!! Form::label('edad', 'Edad:') !!}
    {!! Form::date('edad', null, ['class' => 'form-control']) !!}
</div>

<!-- Procedencia Field -->
<div class="form-group col-sm-6">
    {!! Form::label('procedencia', 'Procedencia:') !!}
    {!! Form::text('procedencia', null, ['class' => 'form-control']) !!}
</div>

<!-- Profesion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('profesion', 'Profesion:') !!}
    {!! Form::text('profesion', null, ['class' => 'form-control']) !!}
</div>

<!-- Pasaporte Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pasaporte', 'Pasaporte:') !!}
    {!! Form::text('pasaporte', null, ['class' => 'form-control']) !!}
</div>

<!-- Ci Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ci', 'Ci:') !!}
    {!! Form::text('ci', null, ['class' => 'form-control']) !!}
</div>

<!-- Celular Field -->
<div class="form-group col-sm-6">
    {!! Form::label('celular', 'Celular:') !!}
    {!! Form::text('celular', null, ['class' => 'form-control']) !!}
</div>

<!-- Referencia Field -->
<div class="form-group col-sm-6">
    {!! Form::label('referencia', 'Referencia:') !!}
    {!! Form::text('referencia', null, ['class' => 'form-control']) !!}
</div>

<!-- Estado Field -->
<div class="form-group col-sm-6">
    {!! Form::label('estado', 'Estado:') !!}
    {!! Form::text('estado', null, ['class' => 'form-control']) !!}
</div>

<!-- Direccion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('direccion', 'Direccion:') !!}
    {!! Form::text('direccion', null, ['class' => 'form-control']) !!}
</div>

<!-- Observaciones Field -->
<div class="form-group col-sm-6">
    {!! Form::label('observaciones', 'Observaciones:') !!}
    {!! Form::text('observaciones', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('clientes.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/clientes/show.blade.php
@extends('layouts.app')

@section('content')
    @include('clientes.show_fields')

    <div class="form-group">
           <a href="{!! route('clientes.index') !!}" class="btn btn-default">Back</a>
    </div>
@endsection