routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

/*Route::get('/', function () {
return view('welcome');
});*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

Auth::routes();

//Route::get('/home', 'HomeController@index');

Route::get('/', 'UserController@direcciona');

/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
 */

Route::group(['prefix' => 'api', 'namespace' => 'API'], function () {
	Route::group(['prefix' => 'v1'], function () {
		require config('infyom.laravel_generator.path.api_routes');
	});
});

Route::group(['middleware' => 'auth'], function () {

	Route::resource('hotels', 'HotelController');

	Route::resource('posts', 'PostController');

	Route::resource('habitaciones', 'HabitacionesController');

	Route::get('muestraHabitaciones/{idHotel}', 'HotelController@muestraHabitaciones');
//Route::get('muestraPisos/{idHotel}', 'PisosController@muestraPisos');
	Route::get('pisosHotel/{idHotel}', 'PisosController@pisosHotel')->name('pisosHotel');
	Route::get('piso/{idHotel}/{idPiso?}', 'PisosController@piso')->name('piso');
	Route::get('pisos/{idHotel}', 'PisosController@pisos')->name('pisos');
	Route::post('guarda_piso/{idPiso?}', 'PisosController@guarda_piso')->name('guarda_piso');
	Route::get('nuevaHabitacion/{idHotel}', 'HabitacionesController@nuevahabitacion');
	Route::get('ingresaPrecio/{idHabitacion}', 'PrecioshabitacionesController@ingresaPrecio');
	Route::get('asignahabitacion', 'ClientesController@asignahabitacion');
	Route::get('asignahabitacion2/{tipo}/{idCliente}/{num_reg?}', 'ClientesController@asignahabitacion2')->name('asignahabitacion2');
	/*Route::controller('datatables', 'PisosController', [
		        'anyData'  => 'datatables.data',
		        'muestraPisos' => 'datatables',
	*/

	Route::resource('clientes', 'ClientesController');

	Route::get('datatables/anyData', 'ClientesController@anyData')->name('datatables.data');
//    Route::get('datatables/getIndex', 'ClientesController@getIndex')->name('datatables');

	Route::resource('pisos', 'PisosController');

	Route::resource('precioshabitaciones', 'PrecioshabitacionesController');

	Route::resource('estudiantes', 'EstudiantesController');

//`Route::auth();

	Route::resource('cajas', 'CajaController');

	Route::resource('flujos', 'FlujoController');

	Route::get('caja/flujos/{idCaja}', 'CajaController@flujos')->name('flujos');

//Route::get('cajas2/{idHotel?}', 'CajaController@index')->name('cajas.index');

	Route::get('caja/ingreso/{idCaja}', 'CajaController@ingreso');
	Route::post('caja/guarda_ingreso', 'CajaController@guarda_ingreso');
	Route::post('retirarpagos', 'CajaController@retirarpagos')->name('retirarpagos');
	Route::post('retirarpagosdia', 'CajaController@retirarpagosdia')->name('retirarpagosdia');

	Route::get('caja/egreso/{idCaja}', 'CajaController@egreso');

	Route::get('soloingresos/{idCaja}', 'CajaController@soloingresos')->name('soloingresos');
	Route::get('soloingresosdia/{idCaja}', 'CajaController@soloingresosdia')->name('soloingresosdia');
	Route::get('ultimosretiros/{idCaja}', 'CajaController@ultimosretiros')->name('ultimosretiros');

	Route::post('caja/guarda_egreso', 'CajaController@guarda_egreso');
	Route::post('caja/eliminar_flujo/{idFlujo}', 'CajaController@eliminar_flujo');

	Route::get('caja/eliminaflujo/{idFlujo}', 'CajaController@eliminaflujo')->name('eliminaflujo');

	Route::get('detalleflujo/{idFlujo}', 'FlujoController@detalleflujo')->name('detalleflujo');

	Route::resource('registros', 'RegistroController');
	Route::get('registros', 'RegistroController@index')->name('registros');
	Route::get('registros/nuevo/{tipo}/{idCliGru}/{idHabitacion}/{idRegistro?}', 'RegistroController@nuevo')->name('nuevoregistro');
	Route::get('registros_calendario', 'RegistroController@calendario')->name('calendario');
	Route::post('registros/guarda_registro/{idRegistro?}', 'RegistroController@guarda_registro')->name('guarda_registro');
//Route::post('registros/nuevos/{idCliente}/{num_reg?}', 'RegistroController@nuevos')->name('nuevos');
	Route::post('registros/guarda_registros/{num_reg?}', 'RegistroController@guarda_registros')->name('guarda_registros');
	Route::get('registros_cliente/{idCliente}', 'RegistroController@registros_cliente')->name('registros_cliente');
	Route::post('registrar_pago', 'RegistroController@registrar_pago')->name('registrar_pago');

	Route::match(['get', 'post'], 'registros/nuevos/{idCliente}/{num_reg?}', 'RegistroController@nuevos')->name('nuevos');

	Route::get('get_num_reg', 'RegistroController@get_num_reg');

	Route::get('direcciona', 'UserController@direcciona')->name('direcciona');

	Route::get('usuarios/', 'UserController@index')->name('usuarios');
	Route::get('usuarios/usuario/{idUsuario?}', 'UserController@usuario')->name('usuario');
	Route::post('usuarios/guarda_usuario/{idUsuario?}', 'UserController@guarda_usuario')->name('guarda_usuario');
	Route::get('usuarios/eliminar/{idUsuario}', 'UserController@eliminar')->name('eliminar');

	Route::get('cambiarhotel/{idHotel}', 'UserController@cambiarhotel')->name('cambiarhotel');

	Route::get('vhabitaciones', 'HabitacionesController@vhabitaciones')->name('vhabitaciones');
	Route::get('informacion_habitacion/{idHabitacion}', 'HabitacionesController@informacion_habitacion')->name('informacion_habitacion');

	Route::resource('categorias', 'CategoriaController');

	Route::resource('facturas', 'FacturaController');
	Route::get('tutoriales', 'TutorialesController@index')->name('tutoriales');
	Route::get('tutoriales/operariotutoriales', 'TutorialesController@operariotutoriales')->name('opetutoriales');

	Route::get('facturar/{idFlujo}', 'FacturaController@facturar')->name('facturar');
	Route::post('generar_factura', 'FacturaController@generar_factura')->name('generar_factura');
	Route::get('factura/{idFactura}', 'FacturaController@factura')->name('factura');

//Route::get('reporte_pagos', 'ReporteController@reporte_pagos')->name('reporte_pagos');

	Route::match(['get', 'post'], 'reporte_pagos', 'ReporteController@reporte_pagos')->name('reporte_pagos');
	Route::match(['get', 'post'], 'repo_pago_regis', 'ReporteController@repo_pago_regis')->name('repo_pago_regis');
	Route::match(['get', 'post'], 'repo_pago_retirados', 'ReporteController@repo_pago_retirados')->name('repo_pago_retirados');

	Route::get('cliente/{idCliente?}', 'ClientesController@cliente')->name('cliente');
	Route::get('adjuntos/{idCliente}', 'ClientesController@adjuntos')->name('adjuntos');

	Route::post('guarda_cliente/{idCliente?}', 'ClientesController@guarda_cliente')->name('guarda_cliente');

	Route::post('guarda_s_adjunto/{idCliente}', 'ClientesController@guarda_s_adjunto')->name('guarda_s_adjunto');

	Route::get('elimina_adjunto/{idAdjunto}', 'ClientesController@elimina_adjunto')->name('elimina_adjunto');

	Route::get('quitarhuesped/{idHospedante}', 'RegistroController@quitarhuesped')->name('quitarhuesped');

	Route::get('msalidahuesped/{idHospedante}', 'RegistroController@msalidahuesped')->name('msalidahuesped');

	Route::get('grupos', 'GrupoController@index')->name('grupos');
	Route::get('registrosgrupos/{idGrupo}', 'GrupoController@registrosgrupos')->name('registrosgrupos');
	Route::get('grupo/{idGrupo?}', 'GrupoController@grupo')->name('grupo');
	Route::get('eliminargrupo/{idGrupo}', 'GrupoController@eliminargrupo')->name('eliminargrupo');
	Route::post('registrapagosg', 'GrupoController@registrapagosg')->name('registrapagosg');

	Route::get('informe_pago_grupo/{idGrupo}', 'GrupoController@informe_pago_grupo')->name('informe_pago_grupo');

	Route::get('marcasalida/{idRegistro}', 'GrupoController@marcasalida')->name('marcasalida');
	Route::get('cancelaregistro/{idRegistro}', 'GrupoController@cancelaregistro')->name('cancelaregistro');
	Route::get('generadeudasgrupos/{idGrupo}', 'GrupoController@generadeudasgrupos')->name('generadeudasgrupos');
	Route::get('generaadelantosgrupos/{idGrupo}', 'GrupoController@generaadelantosgrupos')->name('generaadelantosgrupos');

	Route::get('grupo/{idGrupo}', 'GrupoController@grupo')->name('grupo');
	Route::post('guarda_grupo/{idGrupo}', 'GrupoController@guarda_grupo')->name('guarda_grupo');
	Route::get('addpagoextra/{idRegistro}', 'GrupoController@addpagoextra')->name('addpagoextra');
	Route::post('guarda_pagoextra', 'GrupoController@guarda_pagoextra')->name('guarda_pagoextra');

	Route::match(['get', 'post'], 'pasajeros_reporte', 'ReporteController@pasajeros_reporte')->name('pasajeros_reporte');
	Route::match(['get', 'post'], 'reporte_registros', 'ReporteController@reporte_registros')->name('reporte_registros');

	Route::resource('actividads', 'ActividadController');
	Route::get('actividad/{idCliente}/{idActividad?}', 'ActividadController@actividad')->name('actividad');
	Route::post('guarda_actividad/{idActividad?}', 'ActividadController@guarda_actividad')->name('guarda_actividad');
	Route::get('grupos/eliminapago/{idPago}', 'GrupoController@eliminapago')->name('eliminapago');
	Route::post('grupos/eliminar_pago/{idPago}', 'GrupoController@eliminar_pago');
	Route::get('crono_genera_pagos', 'GrupoController@crono_genera_pagos');

	Route::post('opcioneshab', 'PisosController@opcioneshab')->name('opcioneshab');
	Route::post('guarda_precio_h', 'PisosController@guarda_precio_h')->name('guarda_precio_h');
	Route::post('elimina_precio_h', 'PisosController@elimina_precio_h')->name('elimina_precio_h');

	Route::get('imp_registro/{idRegistro}', 'RegistroController@imp_registro')->name('imp_registro');

app/Models/Caja.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="Caja",
 *      required={nombre, total},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="nombre",
 *          description="nombre",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="total",
 *          description="total",
 *          type="number",
 *          format="float"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class Caja extends Model
{
    use SoftDeletes;

    public $table = 'cajas';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'nombre',
        'total',
        'hotel_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nombre' => 'string',
        'total' => 'decimal'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'nombre' => 'required',
        'total' => 'required'
    ];

    public function hotel(){
        return $this->belongsTo('\App\Models\Hotel');
    }

}

app/Pago.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Pago extends Model
{
    public function getFecha2Attribute()
    {
        $value = $this->fecha;
        if (!empty($value) && "0000-00-00 00:00:00" != $value) {
            $fecha = Carbon::parse($value);
            return $fecha->format('d/m/Y');
        } else {
            return null;
        }
    }
    public function getModificadoAttribute()
    {
        $value = $this->updated_at;
        if (!empty($value) && "0000-00-00 00:00:00" != $value) {
            $fecha = Carbon::parse($value);
            return $fecha->format('d/m/Y');
        } else {
            return null;
        }
    }
    //
    public function registro(){
        //return $this->belongsTo('\App\Models\Pisos');
        return $this->belongsTo('\App\Models\Registro', 'registro_id');
    }
    public function flujo(){
        //return $this->belongsTo('\App\Models\Pisos');
        return $this->belongsTo('\App\Models\Flujo', 'flujo_id');
    }
    public function retiro(){
        //return $this->belongsTo('\App\Models\Pisos');
        return $this->belongsTo('\App\Models\Flujo', 'retiroflujo_id');
    }
}

resources/views/cajas/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <h1 class="pull-left">Edit Caja</h1>
        </div>
    </div>

    @include('core-templates::common.errors')

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                {!! Form::model($caja, ['route' => ['cajas.update', $caja->id], 'method' => 'patch']) !!}
                <div class="box-body">
                    @include('cajas.fields')
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/cajas/egreso.blade.php
{!! Form::open(['url' => 'caja/guarda_egreso']) !!}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Nuevo Egreso</h4>
</div>
<div class="modal-body">
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::text('detalle', null, ['class' => 'form-control','placeholder' => 'Detalle del Egreso','required']) !!}
                </div>
            </div>
        </div>
        <?php
        $maximo_m = 1000000;
        ?>
        @if(Auth::user()->rol == 'Operario')
            <?php $maximo_m = 100;?>
        @endif

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::number('salida', null, ['class' => 'form-control','placeholder' => 'Monto','required','step' => 'any','min' => 0,'max' => $maximo_m]) !!}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!! Form::textarea('observacion', null, ['class' => 'form-control','placeholder' => 'Observacion...','rows' => 3]) !!}
                </div>
            </div>
        </div>
    </div>
</div>
{!! Form::hidden('ingreso',0) !!}
{!! Form::hidden('caja_id',$idCaja) !!}
{!! Form::hidden('user_id',Auth::user()->id) !!}
<div class="modal-footer">
    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Cerrar</button>
    {!! Form::submit('Save', ['class' => 'btn btn-outline pull-left']) !!}
</div>
{!! Form::close() !!}

resources/views/cajas/eliminaflujo.blade.php
{!! Form::open(['url' => 'caja/eliminar_flujo/'.$idFlujo]) !!}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Eliminar flujo</h4>
</div>

@if($flujo->detalle != 'DEUDA DE ENTREGA' && $flujo->detalle != 'DEUDA DE TRASPASO')
    <div class="modal-body">
        <div class="form-group">

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        @if(!empty($ultima_entrega))
                            <h2>NO PUEDE ELIMINAR ESTE FLUJO DEBIDO A QUE YA FUE ENTREGADO</h2>
                        @else
                            @if($flujo->detalle == 'ENTREGA DE CAJA CHICA' || $flujo->detalle == 'TRASPASO DE CAJA CHICA')
                                <h4>NOTA: AL ELIMINAR ESTE FLUJO SE ELIMINA LA ENTREGA COMPLETA (INGERSOS,SALIDAS Y
                                    DEUDAS)</h4>
                            @elseif($flujo->detalle == 'DEUDA CANCELADA')
                                <h4>NOTA: AL ELIMINAR LA DEUDA CANCELADA REGRESA LA DEUDA</h4>
                            @endif

                            <label>Motivo por el cual desea eliminar el flujo??</label>
                            {!! Form::textarea('observacion', null, ['class' => 'form-control','placeholder' => 'Observacion...','rows' => 3,'required']) !!}
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Cerrar</button>
        @if(empty($ultima_entrega))
            {!! Form::submit('Eliminar Flujo', ['class' => 'btn btn-outline pull-left']) !!}
        @endif
    </div>
    {!! Form::close() !!}

@else
    <?php
    $role = Auth::user()->rol;
    ?>
    <div class="modal-body">
        <div class="form-group">

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        @if($role == 'Operario' )
                            <h4>NOTA: SE CANCELARA LA DEUDA Y SE GENERARA UN INGRESO PARA COMPSENSARLO</h4>
                            {!! Form::hidden('opcion','Cancelar deuda') !!}
                        @else
                            <h4>NOTA: AL CANCELAR LA DEUDA SE GENERA UN INGRESO PARA COMPSENSARLO Y EL ELIMINAR NO
                                ELIMINA LA ENTREGA COMPLETA</h4>
                            <label for="">Seleccione la opcion</label>
                            {!! Form::select('opcion',['Cancelar deuda' => 'Cancelar deuda','Eliminar deuda' => 'Eliminar deuda'],null,['class' => 'form-control']) !!}
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Cerrar</button>
        {!! Form::submit('Enviar', ['class' => 'btn btn-outline pull-left']) !!}
    </div>
    {!! Form::close() !!}
@endif

resources/views/cajas/fields.blade.php
<!-- Nombre Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nombre', 'Nombre:') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
</div>

<!-- Total Field -->
<div class="form-group col-sm-6">
    {!! Form::label('total', 'Total:') !!}
    {!! Form::text('total', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('cajas.index') !!}" class="btn btn-default">Cancel</a>
</div>
{!! Form::hidden('hotel_id',Auth::user()->hotel_id) !!}

resources/views/cajas/soloingresos.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="pull-left">PAGOS DE {!! strtoupper($caja->nombre) !!}</h1>

    <div class="clearfix"></div>

    @include('flash::message')

    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="box">
                {!! Form::open(['route' => ['retirarpagos'],'id' => 'form-habit']) !!}
                <div class="box-header">
                    <h3 class="box-title">Ingresos no retirados a detalle <b>Marcados total: <span id="total_mar">0</span> Bs</b>
                    </h3>

                    <div class="box-tools pull-right">
                        <a href="{!! route('soloingresosdia',[$caja->id]) !!}" class="btn btn-info btn-box-tool"
                           style="color: white;"><b>RETIRAR X DIA</b></a>
                        <a href="{!! route('flujos',[$caja->id]) !!}" class="btn btn-primary btn-box-tool"
                        style="color: yellow;"><b>IR A CAJA</b></a>
                        <a href="{!! route('ultimosretiros',[$caja->id]) !!}" class="btn btn-info btn-box-tool"
                           style="color: yellow;"><b>ULTIMOS RETIROS</b></a>

                        {!! Form::button('<b>RETIRAR</b>', ['type' => 'submit', 'class' => 'btn btn-success btn-box-tool', 'style' => 'color: white;','onclick' => "return confirm('Esta seguro de registrar los pagos como retirados?')"]) !!}
                    </div>
                </div>
                <!-- /.box-header -->
                <style>
                    th.centro{
                        text-align: center; !important;
                    }
                </style>
                <div class="box-body no-padding">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th class="centro" align="center">
                                <input type="checkbox" name="todos"
                                       onclick="$('.marcado').prop('checked',$(this).prop('checked'));calculatotal();">
                            </th>
                            <th>Fecha</th>
                            <th>Habitacion</th>
                            <th>Tipo</th>
                            <th>Piso</th>
                            <th>Grupo</th>
                            <th>Monto</th>
                        </tr>
                        </thead>
                        <tbody>                        
                        @foreach($pagos_sr as $pago)
                            <tr>
                                <td align="center">
                                    <input type="checkbox" name="pagos[{!! $pago->id !!}][valor]" class="marcado"
                                           value="{!! $pago->monto_total !!}">
                                </td>
                                <td>{!! $pago->fecha2 !!}</td>
                                <td>{!! $pago->registro->habitacione->nombre !!}</td>
                                <td>{!! $pago->registro->habitacione->categoria->nombre !!}</td>
                                <td>{!! $pago->registro->habitacione->rpiso->nombre !!}</td>
                                <td>{!! $pago->registro->grupo->nombre !!}</td>
                                <td>{!! $pago->monto_total !!}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <br>
                    <div class="row">
                        <div class="form-group col-sm-6">
                            {!! Form::select('ruser_id',$usuarios,null,array('class' => 'form-control','placeholder' => 'Seleccione el que entrega','required')) !!}
                        </div>
                        <div class="form-group col-sm-6">
                            {!! Form::button('<b>RETIRAR</b>', ['type' => 'submit', 'class' => 'btn btn-success btn-block', 'style' => 'color: white;','onclick' => "return confirm('Esta seguro de registrar los pagos como retirados?')"]) !!}
                        </div>
                    </div>
                </div>
            {!! Form::hidden('caja_id',$caja->id,array('id' => 'idcaja')) !!}
            {!! Form::hidden('salida',null,array('id' => 'idsalida')) !!}
            {!! Form::close() !!}
            <!-- /.box-body -->
            </div>
        </div>
    </div>
@endsection

@push('scriptsextras')
<script>
    $('.marcado').click(function () {
        calculatotal();
    });

    function calculatotal() {
        var suma_to = 0.00;
        $('.marcado').each(function (es, elem) {
            if ($(elem).prop('checked')) {
                suma_to = suma_to + parseFloat($(elem).val());
            }
        });
        $('#total_mar').html(suma_to);
        $('#idsalida').val(suma_to);
    }
</script>
@endpush

resources/views/cajas/table.blade.php
<table class="table table-responsive" id="cajas-table">
    <thead>
    <th>Nombre</th>
    <th>Total</th>
    <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($cajas as $caja)
        <tr>
            <td>{!! $caja->nombre !!}</td>
            <td>{!! $caja->total !!}</td>
            <td>
                {!! Form::open(['route' => ['cajas.destroy', $caja->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! url('caja/flujos', [$caja->id]) !!}" title="Flujos de caja"
                       class='btn btn-primary btn-xs'><i class="fa fa-list"></i></a>
                    <?php
                    $role = Auth::user()->rol;
                    ?>
                    @if($role != 'Operario')
                        <a href="{!! route('cajas.edit', [$caja->id]) !!}" class='btn btn-default btn-xs'><i
                                    class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    @endif
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/cajas/ultimosretiros.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="pull-left">PAGOS DE {!! strtoupper($caja->nombre) !!}</h1>

    <div class="clearfix"></div>

    @include('flash::message')

    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">ULTIMOS RETIROS</h3>

                    <div class="box-tools pull-right">
                        <a href="{!! route('flujos',[$caja->id]) !!}" class="btn btn-primary btn-box-tool" style="color: yellow;"><b>IR A CAJA</b></a>
                        <a href="{!! route('soloingresos',[$caja->id]) !!}" class="btn btn-success btn-box-tool" style="color: yellow;"><b>IR A RETIRAR</b></a>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body no-padding">
                    <table class="table table-bordered" id="tabla">
                        <thead>
                        <tr>
                            <th>ID-EGRESO</th>
                            <th>Fecha Retiro</th>
                            <th>Fecha Pago</th>
                            <th>Habitacion</th>
                            <th>Tipo</th>
                            <th>Piso</th>
                            <th>Grupo</th>
                            <th>Monto</th>
                        </tr>
                        </thead>
                        <thead>
                        <tr>
                            <th>ID-EGRESO</th>
                            <th>Fecha Retiro</th>
                            <th>Fecha Pago</th>
                            <th>Habitacion</th>
                            <th>Tipo</th>
                            <th>Piso</th>
                            <th>Grupo</th>
                            <th>Monto</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($pagos_cr as $pago)
                            <tr>
                                <td>{!! $pago->retiro->id !!}</td>
                                <td>{!! $pago->retiro->created_at !!}</td>
                                <td>{!! $pago->fecha2 !!}</td>
                                <td>{!! $pago->registro->habitacione->nombre !!}</td>
                                <td>{!! $pago->registro->habitacione->categoria->nombre !!}</td>
                                <td>{!! $pago->registro->habitacione->rpiso->nombre !!}</td>
                                <td>{!! $pago->registro->grupo->nombre !!}</td>
                                <td>{!! $pago->monto_total !!}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>

            <!-- /.box-body -->
            </div>
        </div>
    </div>
@endsection

@push('scriptsextras')
@include('layouts.partials.jsdatatable')
@endpush