routes/web.php
	Route::resource('pisos', 'PisosController');

	Route::resource('precioshabitaciones', 'PrecioshabitacionesController');

	Route::resource('estudiantes', 'EstudiantesController');

//`Route::auth();

	Route::resource('cajas', 'CajaController');

	Route::resource('flujos', 'FlujoController');

	Route::get('caja/flujos/{idCaja}', 'CajaController@flujos')->name('flujos');

//Route::get('cajas2/{idHotel?}', 'CajaController@index')->name('cajas.index');

	Route::get('caja/ingreso/{idCaja}', 'CajaController@ingreso');
	Route::post('caja/guarda_ingreso', 'CajaController@guarda_ingreso');
	Route::post('retirarpagos', 'CajaController@retirarpagos')->name('retirarpagos');
	Route::post('retirarpagosdia', 'CajaController@retirarpagosdia')->name('retirarpagosdia');

	Route::get('caja/egreso/{idCaja}', 'CajaController@egreso');

	Route::get('soloingresos/{idCaja}', 'CajaController@soloingresos')->name('soloingresos');
	Route::get('soloingresosdia/{idCaja}', 'CajaController@soloingresosdia')->name('soloingresosdia');
	Route::get('ultimosretiros/{idCaja}', 'CajaController@ultimosretiros')->name('ultimosretiros');

	Route::post('caja/guarda_egreso', 'CajaController@guarda_egreso');
	Route::post('caja/eliminar_flujo/{idFlujo}', 'CajaController@eliminar_flujo');

	Route::get('caja/eliminaflujo/{idFlujo}', 'CajaController@eliminaflujo')->name('eliminaflujo');

	Route::get('detalleflujo/{idFlujo}', 'FlujoController@detalleflujo')->name('detalleflujo');

	Route::resource('registros', 'RegistroController');
	Route::get('registros', 'RegistroController@index')->name('registros');
	Route::get('registros/nuevo/{tipo}/{idCliGru}/{idHabitacion}/{idRegistro?}', 'RegistroController@nuevo')->name('nuevoregistro');
	Route::get('registros_calendario', 'RegistroController@calendario')->name('calendario');
	Route::post('registros/guarda_registro/{idRegistro?}', 'RegistroController@guarda_registro')->name('guarda_registro');
//Route::post('registros/nuevos/{idCliente}/{num_reg?}', 'RegistroController@nuevos')->name('nuevos');
	Route::post('registros/guarda_registros/{num_reg?}', 'RegistroController@guarda_registros')->name('guarda_registros');
	Route::get('registros_cliente/{idCliente}', 'RegistroController@registros_cliente')->name('registros_cliente');
	Route::post('registrar_pago', 'RegistroController@registrar_pago')->name('registrar_pago');

	Route::match(['get', 'post'], 'registros/nuevos/{idCliente}/{num_reg?}', 'RegistroController@nuevos')->name('nuevos');

	Route::get('get_num_reg', 'RegistroController@get_num_reg');

	Route::get('direcciona', 'UserController@direcciona')->name('direcciona');

	Route::get('usuarios/', 'UserController@index')->name('usuarios');
	Route::get('usuarios/usuario/{idUsuario?}', 'UserController@usuario')->name('usuario');
	Route::post('usuarios/guarda_usuario/{idUsuario?}', 'UserController@guarda_usuario')->name('guarda_usuario');
	Route::get('usuarios/eliminar/{idUsuario}', 'UserController@eliminar')->name('eliminar');

	Route::get('cambiarhotel/{idHotel}', 'UserController@cambiarhotel')->name('cambiarhotel');

	Route::get('vhabitaciones', 'HabitacionesController@vhabitaciones')->name('vhabitaciones');
	Route::get('informacion_habitacion/{idHabitacion}', 'HabitacionesController@informacion_habitacion')->name('informacion_habitacion');

	Route::resource('categorias', 'CategoriaController');

	Route::resource('facturas', 'FacturaController');
	Route::get('tutoriales', 'TutorialesController@index')->name('tutoriales');
	Route::get('tutoriales/operariotutoriales', 'TutorialesController@operariotutoriales')->name('opetutoriales');

	Route::get('facturar/{idFlujo}', 'FacturaController@facturar')->name('facturar');
	Route::post('generar_factura', 'FacturaController@generar_factura')->name('generar_factura');
	Route::get('factura/{idFactura}', 'FacturaController@factura')->name('factura');

//Route::get('reporte_pagos', 'ReporteController@reporte_pagos')->name('reporte_pagos');

	Route::match(['get', 'post'], 'reporte_pagos', 'ReporteController@reporte_pagos')->name('reporte_pagos');
	Route::match(['get', 'post'], 'repo_pago_regis', 'ReporteController@repo_pago_regis')->name('repo_pago_regis');
	Route::match(['get', 'post'], 'repo_pago_retirados', 'ReporteController@repo_pago_retirados')->name('repo_pago_retirados');

	Route::get('cliente/{idCliente?}', 'ClientesController@cliente')->name('cliente');
	Route::get('adjuntos/{idCliente}', 'ClientesController@adjuntos')->name('adjuntos');

	Route::post('guarda_cliente/{idCliente?}', 'ClientesController@guarda_cliente')->name('guarda_cliente');

	Route::post('guarda_s_adjunto/{idCliente}', 'ClientesController@guarda_s_adjunto')->name('guarda_s_adjunto');

	Route::get('elimina_adjunto/{idAdjunto}', 'ClientesController@elimina_adjunto')->name('elimina_adjunto');

	Route::get('quitarhuesped/{idHospedante}', 'RegistroController@quitarhuesped')->name('quitarhuesped');

	Route::get('msalidahuesped/{idHospedante}', 'RegistroController@msalidahuesped')->name('msalidahuesped');

	Route::get('grupos', 'GrupoController@index')->name('grupos');
	Route::get('registrosgrupos/{idGrupo}', 'GrupoController@registrosgrupos')->name('registrosgrupos');
	Route::get('grupo/{idGrupo?}', 'GrupoController@grupo')->name('grupo');
	Route::get('eliminargrupo/{idGrupo}', 'GrupoController@eliminargrupo')->name('eliminargrupo');
	Route::post('registrapagosg', 'GrupoController@registrapagosg')->name('registrapagosg');

	Route::get('informe_pago_grupo/{idGrupo}', 'GrupoController@informe_pago_grupo')->name('informe_pago_grupo');

	Route::get('marcasalida/{idRegistro}', 'GrupoController@marcasalida')->name('marcasalida');
	Route::get('cancelaregistro/{idRegistro}', 'GrupoController@cancelaregistro')->name('cancelaregistro');
	Route::get('generadeudasgrupos/{idGrupo}', 'GrupoController@generadeudasgrupos')->name('generadeudasgrupos');
	Route::get('generaadelantosgrupos/{idGrupo}', 'GrupoController@generaadelantosgrupos')->name('generaadelantosgrupos');

	Route::get('grupo/{idGrupo}', 'GrupoController@grupo')->name('grupo');
	Route::post('guarda_grupo/{idGrupo}', 'GrupoController@guarda_grupo')->name('guarda_grupo');
	Route::get('addpagoextra/{idRegistro}', 'GrupoController@addpagoextra')->name('addpagoextra');
	Route::post('guarda_pagoextra', 'GrupoController@guarda_pagoextra')->name('guarda_pagoextra');

	Route::match(['get', 'post'], 'pasajeros_reporte', 'ReporteController@pasajeros_reporte')->name('pasajeros_reporte');
	Route::match(['get', 'post'], 'reporte_registros', 'ReporteController@reporte_registros')->name('reporte_registros');

	Route::resource('actividads', 'ActividadController');
	Route::get('actividad/{idCliente}/{idActividad?}', 'ActividadController@actividad')->name('actividad');
	Route::post('guarda_actividad/{idActividad?}', 'ActividadController@guarda_actividad')->name('guarda_actividad');
	Route::get('grupos/eliminapago/{idPago}', 'GrupoController@eliminapago')->name('eliminapago');
	Route::post('grupos/eliminar_pago/{idPago}', 'GrupoController@eliminar_pago');
	Route::get('crono_genera_pagos', 'GrupoController@crono_genera_pagos');

	Route::post('opcioneshab', 'PisosController@opcioneshab')->name('opcioneshab');
	Route::post('guarda_precio_h', 'PisosController@guarda_precio_h')->name('guarda_precio_h');
	Route::post('elimina_precio_h', 'PisosController@elimina_precio_h')->name('elimina_precio_h');

	Route::get('imp_registro/{idRegistro}', 'RegistroController@imp_registro')->name('imp_registro');

	Route::match(['get', 'post'], 'terminos_condiciones', 'HotelController@terminos_condiciones')->name('terminos_condiciones');

	Route::match(['get', 'post'], 'tiempo_cancelar_reg', 'HotelController@tiempo_cancelar_reg')->name('tiempo_cancelar_reg');

	Route::match(['get', 'post'], 'config_logo', 'HotelController@config_logo')->name('config_logo');
	Route::match(['get', 'post'], 'config_hora_lim', 'HotelController@config_hora_lim')->name('config_hora_lim');
	Route::match(['get', 'post'], 'config_hora_camb_fecha', 'HotelController@config_hora_camb_fecha')->name('config_hora_camb_fecha');

	Route::get('transferencia/{idRegistro}', 'GrupoController@transferencia')->name('transferencia');
	Route::post('guarda_transferencia', 'RegistroController@guarda_transferencia')->name('guarda_transferencia');

	Route::get('ajaxpreciosr/{idHabitacion}', 'GrupoController@ajaxpreciosr')->name('ajaxpreciosr');

	Route::get('recibo_retiro/{idFlujo}', 'CajaController@recibo_retiro')->name('recibo_retiro');
	Route::get('recibo_retiroxdia/{idFlujo}', 'CajaController@recibo_retiroxdia')->name('recibo_retiroxdia');

	Route::get('get_cliente_fac/{nit}', 'FacturaController@get_cliente_fac')->name('get_cliente_fac');

	Route::get('registra_responable/{idGrupo}/{idCliente}', 'GrupoController@registra_responable')->name('registra_responable');

	Route::get('insumos/{idHotel?}', 'InsumoController@index')->name('insumos');
	Route::get('insumo/{idInsumo?}', 'InsumoController@insumo')->name('insumo');
	Route::post('guarda_insumo/{idInsumo?}', 'InsumoController@guarda_insumo')->name('guarda_insumo');

	Route::get('eliminar_insumo/{idInsumo}', 'InsumoController@eliminar_insumo')->name('eliminar_insumo');

	Route::get('paquetes', 'PaqueteController@index')->name('paquetes');
	Route::get('paquete/{idPaquete?}', 'PaqueteController@paquete')->name('paquete');
	Route::post('guarda_paquete/{idPaquete?}', 'PaqueteController@guarda_paquete')->name('guarda_paquete');
	Route::get('eliminar_paquete/{idPaquete}', 'PaqueteController@eliminar_paquete')->name('eliminar_paquete');
	Route::get('paquetes', 'PaqueteController@index')->name('paquetes');

	Route::get('ingrediente/{idPaquete}/{idIngrediente?}', 'PaqueteController@ingrediente')->name('ingrediente');
	Route::post('guarda_ingrediente/{idIngrediente?}', 'PaqueteController@guarda_ingrediente')->name('guarda_ingrediente');
	Route::get('eliminar_ingrediente/{idIngrediente}', 'PaqueteController@eliminar_ingrediente')->name('eliminar_ingrediente');

app/Models/Factura.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

/**
 * @SWG\Definition(
 *      definition="Factura",
 *      required={},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="codigo_control",
 *          description="codigo_control",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="cliente",
 *          description="cliente",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="nit",
 *          description="nit",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="nit_p",
 *          description="nit_p",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="importetotal",
 *          description="importetotal",
 *          type="number",
 *          format="float"
 *      ),
 *      @SWG\Property(
 *          property="fecha",
 *          description="fecha",
 *          type="string",
 *          format="date"
 *      ),
 *      @SWG\Property(
 *          property="fecha_limite",
 *          description="fecha_limite",
 *          type="string",
 *          format="date"
 *      ),
 *      @SWG\Property(
 *          property="numero",
 *          description="numero",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="autorizacion",
 *          description="autorizacion",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="qr",
 *          description="qr",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="montoliteral",
 *          description="montoliteral",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class Factura extends Model
{
    use SoftDeletes;

    public $table = 'facturas';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'codigo_control',
        'cliente',
        'nit',
        'nit_p',
        'importetotal',
        'fecha',
        'fecha_limite',
        'numero',
        'autorizacion',
        'qr',
        'montoliteral',
        'created'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'codigo_control' => 'string',
        'cliente' => 'string',
        'nit' => 'string',
        'nit_p' => 'string',
        'fecha' => 'date',
        'fecha_limite' => 'date',
        'numero' => 'integer',
        'autorizacion' => 'integer',
        'qr' => 'string',
        'montoliteral' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    public function getFechaAttribute($value)
    {
        if (!empty($value) && "0000-00-00 00:00:00" != $value) {
            $fecha = Carbon::parse($value);
            return $fecha->format('d/m/Y');
        } else {
            return null;
        }
    }

    public function getFechaLimiteAttribute($value)
    {
        if (!empty($value) && "0000-00-00 00:00:00" != $value) {
            $fecha = Carbon::parse($value);
            return $fecha->format('d/m/Y');
        } else {
            return null;
        }
    }
}

resources/views/facturas/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <h1 class="pull-left">Create New Factura</h1>
        </div>
    </div>

    @include('core-templates::common.errors')

    <div class="row">
    <div class="col-md-12">
                <div class="box box-primary">
        {!! Form::open(['route' => 'facturas.store']) !!}
<div class="box-body">
            @include('facturas.fields')
</div>
        {!! Form::close() !!}
    </div>
    </div>
            </div>
@endsection

resources/views/facturas/edit.blade.php
@extends('layouts.app')

@section('content')
        <div class="row">
            <div class="col-sm-12">
                <h1 class="pull-left">Edit Factura</h1>
            </div>
        </div>

        @include('core-templates::common.errors')

        <div class="row">
        <div class="col-md-12">
                        <div class="box box-primary">

            {!! Form::model($factura, ['route' => ['facturas.update', $factura->id], 'method' => 'patch']) !!}
<div class="box-body">
            @include('facturas.fields')
</div>
            {!! Form::close() !!}
            </div>
                    </div>
        </div>
@endsection

resources/views/facturas/factura.blade.php
@extends('layouts.app')

@section('content')
    <style>
        table.mitablar {
            width: 100%;
        }
    </style>
    <h1 class="pull-left"></h1>
    <a class="btn bg-navy btn-flat margin pull-right" onclick="printDiv('printableArea')" style="margin-top: 25px"
       href="javascript:"> <i class="fa fa-print"></i> IMPRIMIR FACTURA</a>

    <div class="clearfix"></div>

    @include('flash::message')

    <div class="clearfix"></div>

    <div class="box">
        <div class="box-body" id="printableArea">
            <table style="width: 100%;">
                <tr>
                    <td style="width: 35%; text-align: center;">
                        {!! Auth::user()->hotel->nombre !!}<br>
                        {!! Auth::user()->hotel->direccion !!}<br>
                        {!! Auth::user()->hotel->telefonos !!}
                    </td>
                    <td style="width: 30%;" align="center">

                    </td>
                    <td style="width: 35%;">
                        <table style="width: 100%;">
                            <tr>
                                <td>NIT:</td>
                                <td>{!! $factura->nit !!}</td>
                            </tr>
                            <tr>
                                <td>AUTORIZACION:</td>
                                <td>{!! $factura->autorizacion !!}</td>
                            </tr>
                            <tr>
                                <td>FACTURA</td>
                                <td>{!! $factura->numero !!}</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>

            <table style="width: 100%;">
                <tr>
                    <td align="right" style="text-align: right">
                        Actividad Económica: Servicio de Hospedaje
                    </td>
                </tr>
            </table>
            <table style="width: 100%;">
                <tr>
                    <td style="text-align: center;">
                        <h2>FACTURA</h2>
                    </td>
                </tr>
            </table>
            <table style="width: 100%;">
                <tr>
                    <td style="width: 50%;">LA PAZ, <?php echo $fecha ?></td>
                    <td></td>
                </tr>
                <tr>
                    <td style="width: 50%;">Sr.(es).: <?php echo $factura->cliente ?></td>
                    <td style="width: 50%;">NIT: {!! $factura->nit !!}</td>
                </tr>
            </table>
            <div style="width: 100%" align="center">
                <span class="text-center text-bold">DETALLE DE FACTURA</span>
                @if(empty($flujo->descripcion))
                    <table class="table table-bordered">

                        <tbody>
                        <tr>
                            <td>
                                {!! $flujo->detalle !!}
                            </td>
                            <td>
                                {!! $flujo->ingreso !!}
                            </td>
                        </tr>
                        <tr>
                            <td><b>TOTAL: </b></td>
                            <td>{!! $flujo->ingreso !!}</td>
                        </tr>
                        </tbody>

                    </table>
                @else
                    {!! $flujo->descripcion !!}
                @endif
            </div>
        <!--
            <table style="width: 100%;">
                <tr>
                    <td style="width: 50%;">Concepto:</td>
                    <td></td>
                </tr>
                <tr>
                    <td style="width: 50%; text-align: center;"> SERVICIO DE HOSPEDAJE</td>
                    <td style="width: 20%;">Bs</td>
                    <td><?php //echo $factura->importetotal ?></td>
                </tr>
                <tr>
                    <td style="width: 50%; text-align: center;"> TOTAL:</td>
                    <td style="width: 20%;">Bs</td>
                    <td><?php //echo $factura->importetotal ?></td>
                </tr>
            </table>-->
            <table style="width: 100%;">
                <tr>
                    <td colspan="2">
                        SON: <?php echo $factura->montoliteral . ' con ' . $monto_decimales . ' BOLIVIANOS' ?> </td>
                </tr>

                <tr>
                    <td style="width: 45%;">CODIGO DE
                        CONTROL: <?php echo $factura->codigo_control ?></td>
                    <td>FECHA LIMITE DE EMISION: <?php echo $factura->fecha_limite ?></td>
                </tr>
            </table>
            <br>
            <div style="text-align: center; font-size: 11px;">
                "ESTE RECIBO NO ES VÁLIDO PARA CREIDITO FISCAL"
            </div>
            <br>
            <table style="width: 100%;">
                <tr>
                    <td style="width: 15%;">

                    </td>
                    <td>
                        <div id="codigoqr">

                        </div>
                    </td>
                </tr>
            </table>

        </div>
    </div>

@endsection




@push('scriptsextras')
    <script src="{{ asset('/js/jquery.qrcode-0.10.0.js') }}"></script>
    <script>
        var textoqr = "<?php echo $factura->qr; ?>";

        var opcionesQRejmeplar = {
            render: 'image'
            , size: 80
            , background: '#fdfdfd'
            , text: textoqr
        };
        var divSelector = '#codigoqr';
        $(divSelector).qrcode(opcionesQRejmeplar);

        function printDiv(divName) {
            var printContents = document.getElementById(divName).innerHTML;
            var originalContents = document.body.innerHTML;

            document.body.innerHTML = printContents;

            window.print();

            document.body.innerHTML = originalContents;
        }
    </script>
@endpush

resources/views/facturas/fields.blade.php
<!-- Codigo Control Field -->
<div class="form-group col-sm-6">
    {!! Form::label('codigo_control', 'Codigo Control:') !!}
    {!! Form::text('codigo_control', null, ['class' => 'form-control']) !!}
</div>

<!-- Cliente Field -->
<div class="form-group col-sm-6">
    {!! Form::label('cliente', 'Cliente:') !!}
    {!! Form::text('cliente', null, ['class' => 'form-control']) !!}
</div>

<!-- Nit Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nit', 'Nit:') !!}
    {!! Form::text('nit', null, ['class' => 'form-control']) !!}
</div>

<!-- Nit P Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nit_p', 'Nit P:') !!}
    {!! Form::text('nit_p', null, ['class' => 'form-control']) !!}
</div>

<!-- Importetotal Field -->
<div class="form-group col-sm-6">
    {!! Form::label('importetotal', 'Importetotal:') !!}
    {!! Form::text('importetotal', null, ['class' => 'form-control']) !!}
</div>

<!-- Fecha Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fecha', 'Fecha:') !!}
    {!! Form::text('fecha', null, ['class' => 'form-control']) !!}
</div>

<!-- Fecha Limite Field -->
<div class="form-group col-sm-6">
    {!! Form::label('fecha_limite', 'Fecha Limite:') !!}
    {!! Form::text('fecha_limite', null, ['class' => 'form-control']) !!}
</div>

<!-- Numero Field -->
<div class="form-group col-sm-6">
    {!! Form::label('numero', 'Numero:') !!}
    {!! Form::text('numero', null, ['class' => 'form-control']) !!}
</div>

<!-- Autorizacion Field -->
<div class="form-group col-sm-6">
    {!! Form::label('autorizacion', 'Autorizacion:') !!}
    {!! Form::text('autorizacion', null, ['class' => 'form-control']) !!}
</div>

<!-- Qr Field -->
<div class="form-group col-sm-6">
    {!! Form::label('qr', 'Qr:') !!}
    {!! Form::text('qr', null, ['class' => 'form-control']) !!}
</div>

<!-- Montoliteral Field -->
<div class="form-group col-sm-6">
    {!! Form::label('montoliteral', 'Montoliteral:') !!}
    {!! Form::text('montoliteral', null, ['class' => 'form-control']) !!}
</div>

<!-- Created Field -->
<div class="form-group col-sm-6">
    {!! Form::label('created', 'Created:') !!}
    {!! Form::text('created', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('facturas.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/facturas/index.blade.php
@extends('layouts.app')

@section('content')
        <h1 class="pull-left">Facturas</h1>
        <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('facturas.create') !!}">Add New</a>

        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        @include('facturas.table')
        
@endsection

resources/views/facturas/show.blade.php
@extends('layouts.app')

@section('content')
    @include('facturas.show_fields')

    <div class="form-group">
           <a href="{!! route('facturas.index') !!}" class="btn btn-default">Back</a>
    </div>
@endsection

resources/views/facturas/table.blade.php
<table class="table table-responsive" id="facturas-table">
    <thead>
        <th>Codigo Control</th>
        <th>Cliente</th>
        <th>Nit</th>
        <th>Nit P</th>
        <th>Importetotal</th>
        <th>Fecha</th>
        <th>Fecha Limite</th>
        <th>Numero</th>
        <th>Autorizacion</th>
        <th>Qr</th>
        <th>Montoliteral</th>
        <th>Created</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($facturas as $factura)
        <tr>
            <td>{!! $factura->codigo_control !!}</td>
            <td>{!! $factura->cliente !!}</td>
            <td>{!! $factura->nit !!}</td>
            <td>{!! $factura->nit_p !!}</td>
            <td>{!! $factura->importetotal !!}</td>
            <td>{!! $factura->fecha !!}</td>
            <td>{!! $factura->fecha_limite !!}</td>
            <td>{!! $factura->numero !!}</td>
            <td>{!! $factura->autorizacion !!}</td>
            <td>{!! $factura->qr !!}</td>
            <td>{!! $factura->montoliteral !!}</td>
            <td>{!! $factura->created !!}</td>
            <td>
                {!! Form::open(['route' => ['facturas.destroy', $factura->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('facturas.show', [$factura->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('facturas.edit', [$factura->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>